// constants.js

const ADD_NEW_LEAGUE = 'ADD_NEW_LEAGUE';
const ADD_PLAYER_TO_NEW_LEAGUE = 'ADD_PLAYER_TO_NEW_LEAGUE';
const ADD_GAME_TO_NEW_LEAGUE = 'ADD_GAME_TO_NEW_LEAGUE';
const CHANGE_NAME_OF_NEW_LEAGUE = 'CHANGE_NAME_OF_NEW_LEAGUE'

export {
  ADD_NEW_LEAGUE,
  ADD_PLAYER_TO_NEW_LEAGUE,
  ADD_GAME_TO_NEW_LEAGUE,
  CHANGE_NAME_OF_NEW_LEAGUE
};
