// actionNames.js

const ADD_NEW_LEAGUE = 'ADD_NEW_LEAGUE';
const ADD_PLAYER_TO_NEW_LEAGUE = 'ADD_PLAYER_TO_NEW_LEAGUE';
const ADD_GAME_TO_NEW_LEAGUE = 'ADD_GAME_TO_NEW_LEAGUE';
const CHANGE_NAME_OF_NEW_LEAGUE = 'CHANGE_NAME_OF_NEW_LEAGUE';
const SET_CURRENT_LEAGUE = 'SET_CURRENT_LEAGUE';
const Change_Bet = 'Change_Bet';
const Change_Game_Score = 'Change_Game_Score ';

export {
  ADD_NEW_LEAGUE,
  ADD_PLAYER_TO_NEW_LEAGUE,
  ADD_GAME_TO_NEW_LEAGUE,
  CHANGE_NAME_OF_NEW_LEAGUE,
  SET_CURRENT_LEAGUE,
  Change_Bet,
  Change_Game_Score,
};
